FROM ubuntu:18.04

LABEL maintainer="nindanaoto <matsuoka.kotaro@gmail.com>"

# install build dependencies
RUN apt-get update && apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang make libssl-dev libomp-dev git curl libgoogle-perftools-dev

# build and install cmake-3.20.2
RUN curl -fsSL https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2.tar.gz | tar Cxzv /
WORKDIR /cmake-3.20.2
RUN ./bootstrap && make -j$(nproc) && make install

# build TFHE
WORKDIR /
RUN git clone --recursive --depth 1 https://github.com/tfhe/tfhe.git && mkdir tfhe/build
WORKDIR /tfhe/build
RUN cmake ../src -DENABLE_TESTS=on -DENABLE_NAYUKI_PORTABLE=off -DENABLE_NAYUKI_AVX=off -DENABLE_SPQLIOS_AVX=off -DENABLE_SPQLIOS_FMA=on -DCMAKE_BUILD_TYPE=optim && make -j$(nproc)

# build TFHEpp
COPY . /TFHEpp
RUN mkdir /TFHEpp/build
WORKDIR /TFHEpp/build
RUN cmake .. -DENABLE_TEST=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release && make -j$(nproc)
